apiVersion: v1
kind: Service
metadata:
  name: rest-server
spec:
  type: LoadBalancer
  selector:
    app: rest-server
  ports:
    - port: 80        # external port for the service
      targetPort: 5000